export interface Data {
	id: number;
	japanese: string; //hiragana/katana
	romaji: string;
	kanji: {
		onyomi: string;
		kunyomi: string;
	};
	description: string;
	checked: boolean;
	group: string;
	level: "N5" | "N4" | "N3" | "N2" | "N1";
}

export type GroupDataById = Record<string, Data>;

export const dummyData: Data[] = [
	{
		id: 1,
		romaji: "tsukue",
		japanese: "つくえ",
		kanji: {
			onyomi: "-",
			kunyomi: "机",
		},
		description: "Table",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 2,
		romaji: "isu",
		japanese: "いす",
		kanji: {
			onyomi: "-",
			kunyomi: "椅子",
		},
		description: "Chair",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 3,
		romaji: "Tana",
		japanese: "たな",
		kanji: {
			onyomi: "-",
			kunyomi: "棚",
		},
		description: "Shelf",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 4,
		romaji: "Taberu",
		japanese: "たべる",
		kanji: {
			onyomi: "-",
			kunyomi: "食べる",
		},
		description: "Eat",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 5,
		romaji: "Terebi",
		japanese: "テレビ",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Television",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 6,
		romaji: "reizouko",
		japanese: "れいぞうこ",
		kanji: {
			onyomi: "-",
			kunyomi: "冷蔵庫",
		},
		description: "Refrigerator",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 7,
		romaji: "Sentakuki",
		japanese: "せんたくき",
		kanji: {
			onyomi: "-",
			kunyomi: "洗濯機",
		},
		description: "Washing machine",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 8,
		romaji: "kagami",
		japanese: "かがみ",
		kanji: {
			onyomi: "-",
			kunyomi: "鏡",
		},
		description: "Mirror",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 9,
		romaji: "beddo",
		japanese: "ベッド",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Bed",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 10,
		romaji: "futon",
		japanese: "ふとん",
		kanji: {
			onyomi: "-",
			kunyomi: "布団",
		},
		description: "Japanese bedding",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 11,
		romaji: "nichi",
		japanese: "にち",
		kanji: {
			onyomi: "-",
			kunyomi: "日",
		},
		description: "Day",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 12,
		romaji: "hi",
		japanese: "ひ",
		kanji: {
			onyomi: "-",
			kunyomi: "日",
		},
		description: "Sun",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 13,
		romaji: "jitsu",
		japanese: "じつ",
		kanji: {
			onyomi: "-",
			kunyomi: "日",
		},
		description: "Reality",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 14,
		romaji: "suki",
		japanese: "すき",
		kanji: {
			onyomi: "-",
			kunyomi: "好き",
		},
		description: "Like",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 15,
		romaji: "tsuki",

		japanese: "つき",
		kanji: {
			onyomi: "-",
			kunyomi: "月",
		},
		description: "Moon",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 16,
		romaji: "getsuyoubi",
		japanese: "げつようび",
		kanji: {
			onyomi: "-",
			kunyomi: "月曜日",
		},
		description: "Monday",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 17,
		romaji: "kinyoubi",
		japanese: "きんようび",
		kanji: {
			onyomi: "-",
			kunyomi: "金曜日",
		},
		description: "Friday",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 18,
		romaji: "nichiyoubi",
		japanese: "にちようび",
		kanji: {
			onyomi: "-",
			kunyomi: "日曜日",
		},
		description: "Sunday",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 19,
		romaji: "kayoubi",
		japanese: "かようび",
		kanji: {
			onyomi: "-",
			kunyomi: "火曜日",
		},
		description: "Tuesday",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 20,
		romaji: "suiyoubi",
		japanese: "すいようび",
		kanji: {
			onyomi: "-",
			kunyomi: "水曜日",
		},
		description: "Wednesday",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 21,
		romaji: "mokuyoubi",
		japanese: "もくようび",
		kanji: {
			onyomi: "-",
			kunyomi: "木曜日",
		},
		description: "Thursday",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 22,
		romaji: "doa",
		japanese: "ドア",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Door",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 23,
		romaji: "mado",
		japanese: "まど",
		kanji: {
			onyomi: "-",
			kunyomi: "窓",
		},
		description: "Window",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 24,
		romaji: "Kāten",
		japanese: "カーテン",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Curtain",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 25,
		romaji: "Garasu",
		japanese: "ガラス",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Glass",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 26,
		romaji: "hon",
		japanese: "ほん",
		kanji: {
			onyomi: "-",
			kunyomi: "本",
		},
		description: "Book",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 27,
		romaji: "enpitsu",
		japanese: "えんぴつ",
		kanji: {
			onyomi: "-",
			kunyomi: "鉛筆",
		},
		description: "Pencil",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 28,
		romaji: "ka",
		japanese: "か",
		kanji: {
			onyomi: "-",
			kunyomi: "火",
		},
		description: "Fire",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 29,
		romaji: "kane",
		japanese: "かね",
		kanji: {
			onyomi: "-",
			kunyomi: "金",
		},
		description: "Money",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 30,
		romaji: "mizu",
		japanese: "みず",
		kanji: {
			onyomi: "-",
			kunyomi: "水",
		},
		description: "Water",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 31,
		romaji: "sui",
		japanese: "すい",
		kanji: {
			onyomi: "-",
			kunyomi: "水",
		},
		description: "Water",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 32,
		romaji: "houchyo",
		japanese: "ほうちょう",
		kanji: {
			onyomi: "-",
			kunyomi: "包丁",
		},
		description: "Knife",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 33,
		romaji: "supuu-n",
		japanese: "スプーン",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Spoon",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 34,
		romaji: "foku",
		japanese: "フォーク",
		kanji: {
			onyomi: "-",
			kunyomi: "-",
		},
		description: "Fork",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 35,
		romaji: "hashi",
		japanese: "はし",
		kanji: {
			onyomi: "-",
			kunyomi: "箸",
		},
		description: "Chopsticks",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 36,
		romaji: "sara",
		japanese: "さら",
		kanji: {
			onyomi: "-",
			kunyomi: "皿",
		},
		description: "Plate",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 37,
		romaji: "koppu",
		japanese: "コップ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Glass",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 38,
		romaji: "kappu",
		japanese: "カップ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Cup",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 39,
		romaji: "ki",
		japanese: "き",
		kanji: { onyomi: "-", kunyomi: "木" },
		description: "Tree",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 40,
		romaji: "kane",
		japanese: "かね",
		kanji: { onyomi: "-", kunyomi: "金" },
		description: "Money",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 41,
		romaji: "pasokon",
		japanese: "パソコン",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Computer",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 42,
		romaji: "sumaho",
		japanese: "スマホ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Smartphone",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 43,
		romaji: "eakon",
		japanese: "エアコン",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Air conditioner",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 44,
		romaji: "senpuuki",
		japanese: "せんぷうき",
		kanji: { onyomi: "-", kunyomi: "扇風機" },
		description: "Fan",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 45,
		romaji: "airon",
		japanese: "アイロン",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Iron",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 46,
		romaji: "tsuchi",
		japanese: "つち",
		kanji: { onyomi: "-", kunyomi: "土" },
		description: "Soil",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 47,
		romaji: "do",
		japanese: "ど",
		kanji: { onyomi: "-", kunyomi: "土" },
		description: "Soil",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 48,
		romaji: "ishi",
		japanese: "いし",
		kanji: { onyomi: "-", kunyomi: "石" },
		description: "Stone",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 49,
		romaji: "seki",
		japanese: "せき",
		kanji: { onyomi: "-", kunyomi: "石" },
		description: "Stone",
		checked: false,
		group: "1",
		level: "N5",
	},
	{
		id: 50,
		romaji: "kore",
		japanese: "これ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "This (near you)",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 51,
		romaji: "sore",
		japanese: "それ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "That (near them)",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 52,
		romaji: "are",
		japanese: "あれ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "That (Near nobody)",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 53,
		romaji: "dore",
		japanese: "どれ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Which one? W question, who, what, which, when,",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 54,
		romaji: "kono",
		japanese: "この",
		kanji: { onyomi: "-", kunyomi: "-" },
		description:
			"This (near you), it requires a noun after it unlike (これ) kore",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 55,
		romaji: "sono",
		japanese: "その",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "That (near them)",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 56,
		romaji: "ano",
		japanese: "あの",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "That (Near nobody)",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 57,
		romaji: "dono",
		japanese: "どの",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Which one? W question, who, what, which, when,",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 58,
		romaji: "koko",
		japanese: "ここ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Here",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 59,
		romaji: "soko",
		japanese: "そこ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "There",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 60,
		romaji: "asoko",
		japanese: "あそこ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Over there",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 61,
		romaji: "doko",
		japanese: "どこ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Where?",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 62,
		romaji: "dareno",
		japanese: "だれの",
		kanji: { onyomi: "-", kunyomi: "-" },
		description:
			"Whose? Need + Noun, the の (no) is the possesive the plain is dare",
		checked: false,
		group: "2",
		level: "N5",
	},
	{
		id: 63,
		romaji: "mo",
		japanese: "も",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Also (used with は wa and が ga), prefix with noun",
		checked: false,
		group: "3",
		level: "N5",
	},
	{
		id: 64,
		romaji: "dewaarimasen",
		japanese: "ではありません",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Is not, negative of desu",
		checked: false,
		group: "3",
		level: "N5",
	},
	{
		id: 65,
		romaji: "jyanai",
		japanese: "じゃない",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: "Is not, negative of desu",
		checked: false,
		group: "3",
		level: "N5",
	},
	{
		id: 66,
		romaji: "yo",
		japanese: "よ",
		kanji: { onyomi: "-", kunyomi: "-" },
		description:
			"Emphasis, used at the end of a sentence, banana are sweet, you know.",
		checked: false,
		group: "3",
		level: "N5",
	},
	{
		id: 67,
		romaji: "ne",
		japanese: "ね",
		kanji: { onyomi: "-", kunyomi: "-" },
		description: `Right? Used at the end of a sentence
		e.g.
		english: bananawa amai desune.
		japanese: バナナは甘いですね。
		`,
		checked: false,
		group: "3",
		level: "N5",
	},
];
