export interface Data {
	id: number;
	japanese: string; //hiragana/katana
	romaji: string;
	kanji: string;
	onyomi: string;
	kunyomi: string;
	description: string;
	checked: boolean;
	group: string;
	level: "N5" | "N4" | "N3" | "N2" | "N1";
}

export type GroupDataById = Record<string, Data>;

export const dummyData: Data[] = [
	{
		id: 1,
		romaji: "ichi",
		japanese: "いち",
		kanji: "一",
		onyomi: "いち / いつ",
		kunyomi: "ひと / ひと.つ",
		description: "one, ひと.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 2,
		romaji: "ni",
		japanese: "に",
		kanji: "二",
		onyomi: "に",
		kunyomi: "ふた / ふた.つ",
		description: "two, ふた.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 3,
		romaji: "san",
		japanese: "さん",
		kanji: "三",
		onyomi: "さん",
		kunyomi: "み / み.つ",
		description: "three, み.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 4,
		romaji: "shi",
		japanese: "し",
		kanji: "四",
		onyomi: "し",
		kunyomi: "よ / よ.つ / よん",
		description: "four, よ.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 5,
		romaji: "go",
		japanese: "ご",
		kanji: "五",
		onyomi: "ご",
		kunyomi: "いつ / いつ.つ",
		description: "five, いつ.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 6,
		romaji: "roku",
		japanese: "ろく",
		kanji: "六",
		onyomi: "ろく",
		kunyomi: "む / む.つ / むい",
		description: "six, む.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 7,
		romaji: "nana",
		japanese: "なな",
		kanji: "七",
		onyomi: "しち",
		kunyomi: "なな / なな.つ / なの",
		description: "seven, なな.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 8,
		romaji: "hachi",
		japanese: "はち",
		kanji: "八",
		onyomi: "はち",
		kunyomi: "や / や.つ / よう",
		description: "eight, や.つ for a person, 八つ",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 9,
		romaji: "kyuu",
		japanese: "きゅう",
		kanji: "九",
		onyomi: "きゅう",
		kunyomi: "ここの / ここの.つ",
		description: "nine, ここの.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 10,
		romaji: "juu",
		japanese: "じゅう",
		kanji: "十",
		onyomi: "じゅう",
		kunyomi: "とお / とお.つ",
		description: "ten, とお.つ for a person",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 11,
		romaji: "hyaku",
		japanese: "ひゃく",
		kanji: "百",
		onyomi: "ひゃく",
		kunyomi: "",
		description: "hundred",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 12,
		romaji: "sen",
		japanese: "せん",
		kanji: "千",
		onyomi: "せん",
		kunyomi: "",
		description: "thousand",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 13,
		romaji: "Man / Ban",
		japanese: "まん / ばん",
		kanji: "万 / 万",
		onyomi: "まん / ばん",
		kunyomi: "",
		description: "ten thousand",
		checked: false,
		group: "numbers",
		level: "N5",
	},
	{
		id: 14,
		romaji: "Mizu",
		japanese: "みず",
		kanji: "水",
		onyomi: "すい",
		kunyomi: "みず",
		description: "water",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 15,
		romaji: "Ka",
		japanese: "か",
		kanji: "火",
		onyomi: "か",
		kunyomi: "ひ",
		description: "fire",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 16,
		romaji: "Ki",
		japanese: "き",
		kanji: "木",
		onyomi: "もく / ぼく",
		kunyomi: "き / こ",
		description: `tree / wood / timber / forest
    e.g.: Paired with day become 木曜日 (mokuyoubi) - Thursday`,
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 17,
		romaji: "Ten",
		japanese: "てん",
		kanji: "天",
		onyomi: "てん",
		kunyomi: "あまつ / あめ / あま",
		description: `heavens / sky / imperial
    e.g. Paired with emperor become 天皇 (tennou) - emperor
    e.g. Paired with day become 天気 (tenki) - weather
    `,
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 18,
		romaji: "Do",
		japanese: "ど",
		kanji: "土",
		onyomi: "ど / と",
		kunyomi: "つち",
		description: `soil / earth / ground / Turkey
    e.g. Paired with day become 土曜日 (doyoubi) - Saturday`,
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 19,
		romaji: "Kin",
		japanese: "きん",
		kanji: "金",
		onyomi: "きん / こん",
		kunyomi: "かね / かな",
		description: `gold / money / metal
    e.g. Paired with day become 金曜日 (kinyoubi) - Friday`,
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 20,
		romaji: "getsu",
		japanese: "げつ",
		kanji: "月",
		onyomi: "げつ / がつ",
		kunyomi: "つき",
		description: `moon / month
    e.g. Paired with day become 月曜日 (getsuyoubi) - Monday`,
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 21,
		romaji: "Nichi",
		japanese: "にち",
		kanji: "日",
		onyomi: "にち / じつ",
		kunyomi: "ひ / -び / -か",
		description: `day / sun / Japan
    e.g. Paired with day become 日曜日 (nichiyoubi) - Sunday`,
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 22,
		romaji: "Hoku",
		japanese: "ほく",
		kanji: "北",
		onyomi: "ほく",
		kunyomi: "きた",
		description: "North",
		checked: false,
		group: "Direction",
		level: "N5",
	},
	{
		id: 23,
		romaji: "Tou",
		japanese: "とう",
		kanji: "東",
		onyomi: "とう",
		kunyomi: "ひがし",
		description: "East",
		checked: false,
		group: "Direction",
		level: "N5",
	},
	{
		id: 24,
		romaji: "Sei / Sai",
		japanese: "せい / さい",
		kanji: "西",
		onyomi: "せい / さい",
		kunyomi: "にし",
		description: "West",
		checked: false,
		group: "Direction",
		level: "N5",
	},
	{
		id: 25,
		romaji: "Nan",
		japanese: "なん",
		kanji: "南",
		onyomi: "なん",
		kunyomi: "みなみ",
		description: "South",
		checked: false,
		group: "Direction",
		level: "N5",
	},
	{
		id: 26,
		romaji: "Sa",
		japanese: "さ",
		kanji: "左",
		onyomi: "さ",
		kunyomi: "ひだり",
		description: "Left",
		checked: false,
		group: "Direction",
		level: "N5",
	},
	{
		id: 27,
		romaji: "Mi",
		japanese: "み",
		kanji: "右",
		onyomi: "う / ゆう",
		kunyomi: "みぎ",
		description: "Right",
		checked: false,
		group: "Direction",
		level: "N5",
	},
	{
		id: 28,
		romaji: "Nichi / Jitsu",
		japanese: "にち / じつ",
		kanji: "日",
		onyomi: "にち / じつ",
		kunyomi: "ひ / -び / -か",
		description: "day / sun / Japan",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 29,
		romaji: "Getsu / Gatsu",
		japanese: "げつ / がつ",
		kanji: "月",
		onyomi: "げつ / がつ",
		kunyomi: "つき",
		description: "moon / month",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 30,
		romaji: "Ka",
		description: "flower",
		japanese: "か",
		kanji: "花",
		onyomi: "か",
		kunyomi: "はな",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 31,
		romaji: "saakana",
		description: "fish",
		japanese: "さかな",
		kanji: "魚",
		onyomi: "ぎょ",
		kunyomi: "うお / さかな",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 32,
		romaji: "Kuu",
		japanese: "くう",
		kanji: "空",
		onyomi: "くう",
		kunyomi: "そら / あ / から / す",
		description: "sky / kuukou - airport (空港)",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 32,
		romaji: "Yama",
		japanese: "やま",
		kanji: "山",
		onyomi: "さん",
		kunyomi: "やま",
		description: "mountain",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 33,
		romaji: "Kawa",
		japanese: "かわ",
		kanji: "川",
		onyomi: "せん",
		kunyomi: "かわ",
		description: "river",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 34,
		romaji: "U / Ame",
		japanese: "う / あめ",
		kanji: "雨",
		onyomi: "う",
		kunyomi: "あめ / あま",
		description: "rain",
		checked: false,
		group: "Day",
		level: "N5",
	},
	{
		id: 35,
		romaji: "Hon",
		japanese: "ほん",
		kanji: "本",
		onyomi: "ほん",
		kunyomi: "もと",
		description: "book",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 36,
		romaji: "Me",
		japanese: "め",
		kanji: "目",
		onyomi: "もく",
		kunyomi: "め",
		description: "eye",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 37,
		romaji: "Kuchi",
		japanese: "くち",
		kanji: "口",
		onyomi: "こう",
		kunyomi: "くち",
		description: "mouth",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 38,
		romaji: "Mimi",
		japanese: "みみ",
		kanji: "耳",
		onyomi: "じ",
		kunyomi: "みみ",
		description: "ear",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 39,
		romaji: "Te",
		japanese: "て",
		kanji: "手",
		onyomi: "しゅ",
		kunyomi: "て",
		description: "hand",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 40,
		romaji: "Ashi / Ta(riru) / Ta(su)",
		japanese: "あし / た(りる) / た(す)",
		kanji: "足",
		onyomi: "そく",
		kunyomi: "あし / た(りる) / た(す)",
		description: "foot / leg",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 41,
		romaji: "Jin / Nin",
		japanese: "じん / にん",
		kanji: "人",
		onyomi: "じん / にん",
		kunyomi: "ひと",
		description: "person / Jinkou - population (人口)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 42,
		romaji: "Haha",
		japanese: "はは",
		kanji: "母",
		onyomi: "ぼ",
		kunyomi: "はは",
		description: "mother / Sobo - grandmother (祖母)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 43,
		romaji: "Chichi",
		japanese: "ちち",
		kanji: "父",
		onyomi: "ふ",
		kunyomi: "ちち",
		description: "father / Sofu - grandfather (祖父)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 44,
		romaji: "Onna / Me",
		japanese: "おんな / め",
		kanji: "女",
		onyomi: "じょ",
		kunyomi: "おんな / め",
		description: "Female / Josein - 女性",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 45,
		romaji: "Otoko / O",
		japanese: "おとこ / お",
		kanji: "男",
		onyomi: "だん / なん",
		kunyomi: "おとこ / お",
		description: "Man, Male",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 46,
		romaji: "Ko",
		japanese: "こ",
		kanji: "子",
		onyomi: "し",
		kunyomi: "こ",
		description: "child / a child - kodomo (子供)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 47,
		romaji: "Chii(sai) / Ko / O",
		japanese: "ちい(さい) / こ / お",
		kanji: "小",
		onyomi: "しょう",
		kunyomi: "ちい(さい) / こ / お",
		description: "small / little / small size / komugi - wheat (小麦)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 48,
		romaji: "Naka",
		japanese: "なか",
		kanji: "中",
		onyomi: "ちゅう",
		kunyomi: "なか",
		description: `inside / middle / center / nakami - contents (中身) / nakayoku - friendly (仲良く), nakama - friend (仲間)
			ちょうごく - China (中国)	
			e.g. Paired with day become 月曜日 (nichiyoubi) - Sunday`,
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 49,
		romaji: "Oo(kii)",
		japanese: "おお(きい)",
		kanji: "大",
		onyomi: "だい / たい",
		kunyomi: "おお(きい)",
		description:
			"big / large / great / ookii - big (大きい) / daigaku - university (大学)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 50,
		romaji: "Ue / Kami / A(geru/garu)",
		japanese: "うえ / かみ / あ(げる/がる)",
		kanji: "上",
		onyomi: "じょう / しょう",
		kunyomi: "うえ / かみ / あ(げる/がる)",
		description:
			"above / up / over / ue - above (上) / kamisama - God (神様) / ageru - give (上げる)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 51,
		romaji: "Shita / Sa(geru) / O(rosu) / Ku(daru)",
		japanese: "した / さ(げる) / お(ろす) / く(だる)",
		kanji: "下",
		onyomi: "か / げ",
		kunyomi: "した / さ(げる) / お(ろす) / く(だる)",
		description:
			"below / down / under / shita - below (下) / sagaru - hang (下がる) / orosu - lower (下ろす) / kudaru - go down (下る)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 52,
		romaji: "Nani",
		japanese: "なに",
		kanji: "何",
		onyomi: "か",
		kunyomi: "なに / なん",
		description: "what / nani - what (何) / what time - nanji (何時)",
		checked: false,
		group: "N5",
		level: "N5",
	},
	{
		id: 53,
		romaji: "Iku / Yu(ku) / Okona(u)",
		japanese: "いく / ゆ(く) / おこな(う)",
		kanji: "行",
		onyomi: "こう / ぎょう",
		kunyomi: "いく / ゆ(く) / おこな(う)",
		description:
			"go / yuku - go (行く) / okonau - do (行う) / gakkou - school (学校)",
		checked: false,
		group: "N5",
		level: "N5",
	},
];
