import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HydrationOverlay } from "@builder.io/react-hydration-overlay";
const inter = Inter({ subsets: ["latin"] });
import Providers from "./provider";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<HydrationOverlay>
				<body className={inter.className}>
					<Providers>{children}</Providers>
				</body>
			</HydrationOverlay>
		</html>
	);
}
